"use client";

import { useState } from "react";
import { addNewItem, fetchItem, editItem, removeItem, fetchItems } from "@/actions/example";
import { getClientEnv } from "@/lib/env";

export interface SmokeTestResult {
  name: string;
  status: "pass" | "fail" | "skip" | "running";
  latency?: number;
  error?: string;
}

async function timedTest(
  name: string,
  fn: () => Promise<void>,
): Promise<SmokeTestResult> {
  const start = performance.now();
  try {
    await fn();
    return {
      name,
      status: "pass",
      latency: Math.round(performance.now() - start),
    };
  } catch (err) {
    return {
      name,
      status: "fail",
      latency: Math.round(performance.now() - start),
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

/** Check if user has a session cookie (client-side check). */
function hasSessionCookie(): boolean {
  // session cookie is httpOnly — not readable from JS.
  // Use /api/auth/session to check instead.
  return false; // Can't check directly; use async check below.
}

async function checkAuth(): Promise<boolean> {
  try {
    const res = await fetch("/api/auth/session", { credentials: "same-origin" });
    return res.ok;
  } catch {
    return false;
  }
}

export function useSmokeTest() {
  const [results, setResults] = useState<SmokeTestResult[]>([]);
  const [running, setRunning] = useState(false);

  async function runTests() {
    setRunning(true);
    setResults([]);
    const all: SmokeTestResult[] = [];
    let createdId: string | null = null;

    // Check auth before running CRUD tests
    const isAuthenticated = await checkAuth();

    try {
      if (isAuthenticated) {
        // 1. Create Item
        const createResult = await timedTest("Create Item", async () => {
          const item = await addNewItem({
            title: "[SMOKE-TEST] Health Check",
            description: "Auto-generated by dashboard smoke test",
          });
          createdId = item.id;
        });
        all.push(createResult);
        setResults([...all]);

        // 2. Read Item
        if (createdId) {
          const readResult = await timedTest("Read Item", async () => {
            await fetchItem(createdId!);
          });
          all.push(readResult);
          setResults([...all]);

          // 3. Update Item
          const updateResult = await timedTest("Update Item", async () => {
            await editItem(createdId!, { title: "[SMOKE-TEST] Updated" });
          });
          all.push(updateResult);
          setResults([...all]);

          // 4. Delete Item
          const deleteResult = await timedTest("Delete Item", async () => {
            await removeItem(createdId!);
            createdId = null;
          });
          all.push(deleteResult);
          setResults([...all]);
        }

        // 5. List Items
        const listResult = await timedTest("List Items", async () => {
          await fetchItems(0, 1);
        });
        all.push(listResult);
        setResults([...all]);
      } else {
        // Skip CRUD tests — user not authenticated
        const crudTests = ["Create Item", "List Items"];
        for (const name of crudTests) {
          all.push({ name, status: "skip", error: "Login required" });
        }
        setResults([...all]);
      }

      // 6. Health Check (direct, no auth required — always runs)
      const healthResult = await timedTest("Health Check", async () => {
        const env = getClientEnv();
        const res = await fetch(
          `${env.NEXT_PUBLIC_API_URL}/health/live`,
        );
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
      });
      all.push(healthResult);
      setResults([...all]);
    } finally {
      // Cleanup: try to delete orphan if create succeeded but delete failed
      if (createdId) {
        try {
          await removeItem(createdId);
        } catch {
          // Best-effort cleanup
        }
      }
      setRunning(false);
    }
  }

  return { results, running, runTests };
}
